### ISSUE TITLE
EPIC: Documentation MVP

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#133]
We need to get Kobweb documented (at https://kobweb.varabyte.com).

Instead of creating a bunch of one off bugs, I've decided to collect everything here, both as it will be easier to update when I realize an item is missing, but also people can view this as a roadmap for what's to come.

Note that there will be a separate bug for guides, which are more about workflows. These issues or for going into detail about specific features.

# Kobweb
- [ ] Installation
- [ ] Project philosophy
   * The different layers, e.g. core, silk, gradle plugins, ...
   * Extending Compose for Web
- [ ] Project layout
   * components
   * pages
   * resources
      * public
      * markdown
- [ ] App
- [ ] Page / routeOverride
- [ ] PackageMapping
- [ ] PageContext / query parameters / dynamic routes
- [ ] Link / Router / OpenLinkStrategy
- [ ] Setting the Error page

# Silk

- [ ] Modifier
- [ ] Theming / Color Mode / Colors / Shapes
- [ ] ComponentStyle / ComponentVariant
   * And the "base" variants
- [ ] Breakpoints
- [ ] InitSilk

# Silk Components
- [ ] Surface
- [ ] Link
- [ ] Image
- [ ] Canvas (2d and Gl)
- [ ] Divider
- [ ] SimpleGrid
- [ ] Text
- [ ] TOC

# Markdown

- [ ] Markdown resources
- [ ] Configuring markdown output

# Kobweb CLI
- [ ] kobweb list
- [ ] kobweb create
- [ ] kobweb export
- [ ] kobweb run
- [ ] kobweb stop
