### ISSUE TITLE
EPIC: Guide Documentation

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#134]
We need to get Kobweb documented (at https://kobweb.varabyte.com).

This epic is reserved for higher level guides. These represent common user stories that walk a user through many steps.

- [ ] Creating and running a project
- [ ] Exporting a project and running in production mode
   * Kobweb layout
   * Static layout
- [ ] Running your project on....
   * A static website hoster
   * Google Cloud Run (with a Docker file)
